import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import fs from 'node:fs/promises';
import path from 'path';
import os from 'os';
import YAML from 'yaml';
import { loadDescriptor, MIN_DESCRIPTOR_VERSION } from '../../src/core/sysprompt.js';
import type { ProjectDescriptor } from '../../src/types.js';

// staleness detection when loading descriptors generated by older LAI versions

describe('loadDescriptor version staleness warning', () => {
    let tempDir: string;
    let consoleLogSpy: ReturnType<typeof vi.spyOn>;

    beforeEach(async () => {
        tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'lai-descriptor-version-'));
        consoleLogSpy = vi.spyOn(console, 'log').mockImplementation(() => {});
    });

    afterEach(async () => {
        consoleLogSpy.mockRestore();
        await fs.rm(tempDir, { recursive: true, force: true });
    });

    const writeDescriptor = async (descriptor: Partial<ProjectDescriptor>): Promise<string> => {
        const descriptorPath = path.join(tempDir, 'test.descriptor.yml');
        await fs.writeFile(descriptorPath, YAML.stringify(descriptor), 'utf-8');
        return descriptorPath;
    };

    const warned = (): boolean =>
        consoleLogSpy.mock.calls.some((call: string[]) =>
            call.some((arg) => typeof arg === 'string' && /outdated format/.test(arg)),
        );

    it('warns when the descriptor version is older than the minimum', async () => {
        const descriptorPath = await writeDescriptor({ version: '0.3.3', langiumConfig: './langium-config.json' });
        await loadDescriptor(descriptorPath);
        expect(warned()).toBe(true);
    });

    it('warns when the descriptor has no version at all', async () => {
        const descriptorPath = await writeDescriptor({ langiumConfig: './langium-config.json' });
        await loadDescriptor(descriptorPath);
        expect(warned()).toBe(true);
    });

    it('does not warn when the descriptor version meets the minimum', async () => {
        const descriptorPath = await writeDescriptor({
            version: MIN_DESCRIPTOR_VERSION,
            langiumConfig: './langium-config.json',
        });
        await loadDescriptor(descriptorPath);
        expect(warned()).toBe(false);
    });

    it('does not warn for a version newer than the minimum, ignoring prerelease suffixes', async () => {
        const descriptorPath = await writeDescriptor({
            version: '0.5.0-next3',
            langiumConfig: './langium-config.json',
        });
        await loadDescriptor(descriptorPath);
        expect(warned()).toBe(false);
    });
});
