import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import YAML from 'yaml';
import type { ProjectDescriptor, ValidatorService } from '../types.js';
import { pathExists } from '../utils/fs.js';
import { warning } from '../utils/console.js';
import { extractValidatorChecks, formatValidatorSummary } from './validator-summary.js';

// system prompt generation from descriptor templates

/**
 * Oldest LAI version whose descriptor schema is compatible with the current one.
 * Bump this only when the descriptor shape actually changes (as it did in 0.4.0,
 * when all descriptor properties moved to camelCase). Descriptors stamped with an
 * older `version` — or with no version at all — are flagged as stale on load.
 */
export const MIN_DESCRIPTOR_VERSION = '0.4.0';

/**
 * Compare two dotted version strings (e.g. '0.3.3' vs '0.4.0') numerically.
 * Returns a negative number if `a` < `b`, zero if equal, positive if `a` > `b`.
 * Non-numeric segments (e.g. a '-next11' prerelease suffix) are ignored.
 */
function compareVersions(a: string, b: string): number {
    const parse = (v: string) => v.split('.').map((seg) => parseInt(seg, 10) || 0);
    const av = parse(a);
    const bv = parse(b);
    const len = Math.max(av.length, bv.length);
    for (let i = 0; i < len; i++) {
        const diff = (av[i] ?? 0) - (bv[i] ?? 0);
        if (diff !== 0) {
            return diff;
        }
    }
    return 0;
}

/**
 * Warn (without blocking) when a descriptor was generated by a version of LAI
 * older than {@link MIN_DESCRIPTOR_VERSION}, or carries no version at all. Such
 * descriptors may use the old schema and should be regenerated.
 */
function warnIfDescriptorOutdated(descriptor: ProjectDescriptor): void {
    const version = descriptor.version;
    if (!version || compareVersions(version, MIN_DESCRIPTOR_VERSION) < 0) {
        warning(
            `This descriptor was generated by an older version of Langium AI` +
                `${version ? ` (${version})` : ''} and may use an outdated format. ` +
                `Regenerate it with 'lai gen descriptor' to get an up-to-date descriptor.`,
        );
    }
}

/**
 * Line count above which inlining a validator verbatim is discouraged in favour
 * of a statically-extracted check summary. Large validators otherwise dominate
 * the prompt with implementation detail an LLM does not need.
 */
export const VALIDATOR_INLINE_LINE_THRESHOLD = 1000;

/**
 * Options controlling system prompt generation.
 */
export interface GenerateSystemPromptOptions {
    /**
     * Whether to inline the validator source verbatim. When false (the default
     * for large validators), a statically-extracted check summary is emitted
     * instead, pointing at the validator file.
     */
    inlineValidator?: boolean;
}

export async function loadDescriptor(descriptorPath: string): Promise<ProjectDescriptor> {
    const content = await readFile(descriptorPath, 'utf-8');
    const descriptor: ProjectDescriptor = YAML.parse(content);
    warnIfDescriptorOutdated(descriptor);
    return descriptor;
}

/**
 * Resolve the descriptor's validators as a normalized list.
 */
function resolveValidators(descriptor: ProjectDescriptor): ValidatorService[] {
    return descriptor.services?.validators ?? [];
}

/**
 * Count the total lines across the descriptor's validator sources, or undefined
 * if there are no validators or none of their files exist. Lets callers decide
 * up-front whether to inline them.
 */
export async function countValidatorLines(descriptor: ProjectDescriptor, cwd: string): Promise<number | undefined> {
    const validators = resolveValidators(descriptor);
    if (validators.length === 0) {
        return undefined;
    }

    let total = 0;
    let found = false;
    for (const validator of validators) {
        const validatorPath = path.join(cwd, validator.path);
        if (!(await pathExists(validatorPath))) {
            continue;
        }
        const content = await readFile(validatorPath, 'utf-8');
        total += content.split('\n').length;
        found = true;
    }

    return found ? total : undefined;
}

/**
 * Generate a suitable default system prompt from our language descriptor
 */
export async function generateSystemPrompt(
    descriptor: ProjectDescriptor,
    options: GenerateSystemPromptOptions = {},
): Promise<string> {
    const cwd = process.cwd();

    // load all referenced content from descriptor
    const content = await loadContent(descriptor, cwd, options);

    // process template sections
    const processedPrompt = processContent(content, descriptor);

    return processedPrompt;
}

/**
 * Takes a list of items and prints out an 'X, Y, and Z' style string
 */
function prettyPrintArray(items: string[]): string {
    const parts: string[] = [];
    for (let x = items.length - 1; x >= 0; x--) {
        if (x === items.length - 1 && x > 0) {
            // insert ', and' before
            parts.unshift(`and ${items[x]}`);
        } else {
            parts.unshift(items[x]);
        }
    }
    return parts.join(', ');
}

/**
 * Prepares template content
 */
async function loadContent(
    descriptor: ProjectDescriptor,
    cwd: string,
    options: GenerateSystemPromptOptions,
): Promise<Array<[string, string]>> {
    const content: Array<[string, string]> = [];

    const languageNames: string[] = descriptor.languages.map((l) => l.name);
    const joinedNames = prettyPrintArray(descriptor.languages.map((l) => l.name));

    // introduction
    content.push([
        'Introduction',
        [
            `You are an AI assistant for working with the ${joinedNames} domain-specific language${languageNames.length > 1 ? 's' : ''}.`,
            'You can both explain existing DSL programs and write new ones.',
        ].join('\n'),
    ]);

    // grammars for each language
    for (const l of descriptor.languages) {
        const grammar = l.grammar;
        const grammarPath = path.join(cwd, grammar);
        if (await pathExists(grammarPath)) {
            const grammarContent = await readFile(grammarPath, 'utf-8');
            content.push([
                `Grammar for ${l.name}`,
                `The language grammar is defined as follows:\n\n\`\`\`langium\n${grammarContent}\n\`\`\``,
            ]);
        }
    }

    // built-in library definitions
    if (descriptor.builtins) {
        for (let x = 0; x < descriptor.builtins.length; x++) {
            const builtin: string = descriptor.builtins[x];
            const builtinsPath = path.join(cwd, builtin);
            if (await pathExists(builtinsPath)) {
                const builtinsContent = await readFile(builtinsPath, 'utf-8');

                let message: string;
                if (descriptor.languages.length > 1) {
                    // multi-language
                    message = `The following built-ins are available for their respective language in this project. \n\n\`\`\`\n${builtinsContent}\n\`\`\``;
                } else {
                    // single language
                    message = `The following built-ins are available by default in ${descriptor.languages[0].name}. These are always in scope and do not need to be imported or defined by the user.\n\n\`\`\`\n${builtinsContent}\n\`\`\``;
                }

                content.push([`Built-in Library${descriptor.builtins.length > 1 ? ` ${x + 1}` : ''}`, message]);
            }
        }
    }

    // validation rules — one section per validator. multi-language projects wire
    // one validator per language, so each is surfaced (labeled by language when known).
    const validators = resolveValidators(descriptor);
    const multipleValidators = validators.length > 1;
    for (const validator of validators) {
        const validatorPath = path.join(cwd, validator.path);
        if (!(await pathExists(validatorPath))) {
            continue;
        }
        const validatorContent = await readFile(validatorPath, 'utf-8');
        // qualify the heading by language when there's more than one validator
        const heading =
            multipleValidators && validator.language
                ? `Validation Rules for ${validator.language}`
                : 'Validation Rules';
        content.push([heading, buildValidatorSection(validator.path, validatorContent, options)]);
    }

    // take first 3 examples
    if (descriptor.examples && descriptor.examples.length > 0) {
        // only pick 2 examples that have <= 200 * 70 bytes
        // (arbitrary cutoff, assuming lines aren't longer than 70 characters and we have no more than 200 of them)
        const pickedExamples: string[] = [];
        for (const ex of descriptor.examples ?? []) {
            const examplePath = path.join(cwd, ex.file);
            let exampleContent: string | undefined;
            if (await pathExists(examplePath)) {
                exampleContent = await readFile(examplePath, 'utf-8');
            }

            if (exampleContent && exampleContent.length <= 200 * 70) {
                // within bounds, let's take it!
                pickedExamples.push(
                    `#### ${ex.name}\n${ex.description}\n${ex.tags ? `Tags: ${ex.tags.join(', ')}` : ''}\n\n\`\`\`\n${exampleContent}\n\`\`\``,
                );
            }

            if (pickedExamples.length === 2) {
                // all set
                break;
            }
        }

        content.push(['Examples', `Example programs:\n\n${pickedExamples.join('\n\n')}`]);
    }

    // inline documentation (first 2)
    if (descriptor.documentation && descriptor.documentation.length > 0) {
        const docsToLoad = descriptor.documentation.slice(0, 2);
        const docContents = docsToLoad.map((doc) => {
            if (doc.src.startsWith('http://') || doc.src.startsWith('https://')) {
                return `- [${doc.description}](${doc.src})`;
            } else {
                return `- ${doc.description}: ${doc.src}`;
            }
        });

        let name: string;
        if (descriptor.languages.length > 1) {
            name = `for this project's languages`;
        } else {
            name = `for ${descriptor.languages[0].name}`;
        }

        content.push([
            'Documentation',
            `Here's documentation ${name}, relevant for understanding what it is and how to work with it.\n\n${docContents.join('\n')}`,
        ]);
    }

    // capabilities
    content.push([
        'Capabilities',
        [
            `When working with ${prettyPrintArray(descriptor.languages.map((l) => l.name))}:`,
            '- Explain the meaning and behavior of existing programs',
            '- Write new programs that follow the grammar and validation rules',
            '- Help users understand language features and best practices',
            '- Debug and fix issues in DSL code',
        ].join('\n'),
    ]);

    return content;
}

/**
 * Build the validation-rules section, either inlining the validator source
 * verbatim or emitting a statically-extracted summary that points at the file.
 * Falls back to inlining when no checks could be extracted, so we never emit an
 * empty summary.
 */
function buildValidatorSection(
    validatorRef: string,
    validatorContent: string,
    options: GenerateSystemPromptOptions,
): string {
    if (!options.inlineValidator) {
        const groups = extractValidatorChecks(validatorContent);
        if (groups.length > 0) {
            return formatValidatorSummary(validatorRef, groups);
        }
        // extraction failed - fall through to inlining rather than emit nothing
    }
    return `Semantic validation rules:\n\n\`\`\`typescript\n${validatorContent}\n\`\`\``;
}

/**
 * Processes content into a system prompt
 */
function processContent(content: Array<[string, string]>, descriptor: ProjectDescriptor): string {
    const sections = content
        .map(([name, content]) => {
            return `### ${name}\n\n${content}`;
        })
        .join('\n\n');
    const names = prettyPrintArray(descriptor.languages.map((l) => l.name));
    const header = `# ${names} Language System Prompt\n\n`;
    return header + '\n' + sections;
}

export async function saveSystemPrompt(syspromptPath: string, content: string): Promise<string> {
    const cwd = process.cwd();
    const fullPath = path.join(cwd, syspromptPath);

    // write sysprompt as markdown
    await writeFile(fullPath, content, 'utf-8');
    return fullPath;
}
